# Setup
title: Danqing Wang
description: 王丹青
url: https://dqwang122.github.io
avatar: /assets/images/me.jpg
paginate: 5
permalink: pretty
cover_image: /assets/images/school.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Optimize Jekyl SEO Tag
twitter:
  username: dqwang122
  card: summary
logo: logo.png
social:
  name: Danqing Wang
  links:
    - https://twitter.com/dqwang122
    - https://github.com/dqwang122 
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Danqing Wang
  url: https://dqwang122.github.io/
  email: dqwang122@gmail.com
